name: Continuous Integration

on:
    push:
        paths:
            - '**.php'
            - 'phpunit.xml.dist'
    pull_request:
        paths:
            - '**.php'
            - 'phpunit.xml.dist'

jobs:

    run-tests:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        name: "Test - PHP: ${{ matrix.php }} - Laravel - ${{ matrix.stability }}"
        runs-on: ubuntu-latest
        env:
            APP_ENV: local
            APP_DEBUG: false
            APP_KEY: "base64:Q9k9BFjDKZGWlB/Veksz5gs+ltXZetZCxLSO/PFrJEE="
            COOKIE_KEY: "F6Cr0puOhPD@K8lPl609OL6kRjf9JhLh"
            DB_CONNECTION: mysql
            DB_HOST: 127.0.0.1
            DB_DATABASE: app
            DB_USERNAME: root
            DB_PASSWORD: password
            DB_PREFIX: testing_
            REDIS_HOST: 127.0.0.1
            REDIS_PASSWORD: null
            REDIS_PREFIX: app_testing_
            REDIS_CURRENCY_PREFIX: "app_testing_currency:exchange:"
            CACHE_DRIVER: redis
            CACHE_PREFIX: cache_
            QUEUE_CONNECTION: redis
            SESSION_DRIVER: redis
        # Docs: https://docs.github.com/en/actions/using-containerized-services
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: password
                    MYSQL_DATABASE: app
                ports:
                    - 3306/tcp
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
            redis:
                image: redis
                ports:
                    - 6379/tcp
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        strategy:
            fail-fast: false
            matrix:
                php: ['8.1']
                stability: [prefer-stable, prefer-lowest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # Docs: https://github.com/shivammathur/setup-php
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: pcntl, mbstring, dom, fileinfo, pdo, mysqli, pdo_mysql, intl, gd, redis-5.3.7
                ini-values: error_reporting=E_ALL
                tools: composer:v2
                coverage: pcov

            - name: Install Composer Dependencies
              run: |
                 composer install --no-interaction --no-scripts --no-progress --prefer-dist --ansi --optimize-autoloader
                 composer run-script post-root-package-install
                 composer run-script post-autoload-dump

            - name: PHPUnit Testing
              run: composer tests
              env:
                DB_PORT: ${{ job.services.mysql.ports['3306'] }}
                REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

            - name: Generate Test Coverage Badge
              uses: timkrase/phpunit-coverage-badge@v1.2.0
              with:
                report: report/clover-coverage.xml
                report_type: clover
                coverage_badge_path: 'badge-coverage.svg'
                push_badge: true
                repo_token: ${{ secrets.GITHUB_TOKEN }}
